AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CoffeeBotMain
    Type: AWS::Lambda::Function
    Properties:
        Code:
            S3Bucket: "coffee-bot-artifacts"
            S3Key: "lambda_function.py"
        Description: "coffee-bot-dev main function"
        Envrionment:
            Variables:
                SLACK_CHANNEL: coffebot-dev
                SLACK_TOKEN: xoxb-3422906695-407098847860-wFMzb1cNCHIbQzAvt9Lb8OSP
        Handler: lambda_function.lambda_handler
        Role: service-role/coffeebot-dev
        Runtime: python3.6